---
fs3combat:
  default_npc_type: 'Normal'
  npc_types:
    Target:
      Default: 1
    Trivial:
      Default: 3
      Firearms: 4
      Archery: 4
      Melee: 4
      Wounds: 20
    Easy:
      Default: 5
      Firearms: 6
      Archery: 6
      Melee: 6
      Wounds: 10
    Normal:
      Default: 7
      Archery: 8
      Firearms: 8
      Melee: 8
      Wounds: 0
    Hard:
      Default: 9
      Archery: 10
      Firearms: 10
      Melee: 10
      Wounds: -5
    Difficult:
      Default: 11
      Archery: 12
      Firearms: 12
      Melee: 12
      Wounds: -10
    Nightmare:
      Default: 13
      Archery: 14
      Firearms: 14
      Melee: 14
      Wounds: -15
    Impossible:
      Default: 21
      Archery: 23
      Firearms: 23
      Melee: 23
      Wounds: -25
