---
fs3combat:
  default_npc_type: 'Normal'
  npc_types:
    Target:
      Default: 1
    Trivial:
      Default: 3
      Firearms: 4
      Archery: 4
      Melee: 4
      Wounds: 20
    Easy:
      Default: 5
      Firearms: 6
      Archery: 6
      Melee: 6
      Wounds: 10
    Normal:
      Default: 7
      Archery: 7
      Firearms: 7
      Melee: 7
      Wounds: 0
    Hard:
      Default: 8
      Archery: 9
      Firearms: 9
      Melee: 9
      Wounds: -5
    Difficult:
      Default: 10
      Archery: 11
      Firearms: 11
      Melee: 11
      Wounds: -10
    Nightmare:
      Default: 12
      Archery: 13
      Firearms: 13
      Melee: 13
      Wounds: -15
    Impossible:
      Default: 20
      Archery: 22
      Firearms: 22
      Melee: 22
      Wounds: -25
