---
fs3skills:
  action_dots_beyond_chargen_max: 5
  allow_advantages_xp: false
  attr_dots_beyond_chargen_max: 2
  advantage_dots_beyond_chargen_max: 2
  days_between_learning: 0
  max_xp_hoard: 10
  periodic_xp: 2
  xp_costs:
    language:
      '1': 4
      '2': 12
    action:
      '1': 2
      '2': 6
      '3': 8
      '4': 14
      '5': 18
      '6': 22
      '7': 28
    background:
      '1': 8
      '2': 16
    attribute:
      '1': 1
      '2': 8
      '3': 18
    advantage:
      '1': 4
      '2': 12
  xp_cron:
    day_of_week:
    - Sat
    hour:
    - 21
    minute:
    - 0
