---
website:
  achievements:
    wiki_create:
      type: portal
      message: Created a wiki page.
    wiki_edit:
      type: portal
      message: Edited a wiki page.
  allow_html_in_markdown: true
  character_gallery_group: Origin
  character_gallery_subgroup: ""
  left_sidebar: false
  max_folder_size_kb: 25000
  max_upload_size_kb: 5550
  restricted_pages:
  - home
  - inc:*
  - world:*
  - guide:*
  - faq:*
  - dangers:*
  - system:*
  - about_us
  - dangers
  - faq
  - guides
  - policies
  - staff team
  - system
  - world
  sitemap_update_cron:
    hour:
    - 2
    minute:
    - 17
  top_navbar:
  - title: Intro
    menu:
    - id: guide:join_us
      title: Join Us
      route: wiki-page
    - title: Create a Character
      route: chargen
    - title: Roster Characters
      route: roster
    - divider: true
    - id: about_us
      title: About Red Planet
      route: wiki-page
  - title: Game
    menu:
    - id: policies
      title: Policies
      route: wiki-page
    - id: staff_team
      title: Staff Team
      route: wiki-page
    - divider: true
    - title: Who's Online
      route: who
    - title: Forum
      route: forum
    - title: Mail
      route: mail
    - title: Events
      route: events
    - divider: true
    - id: guide
      title: Guides
      route: wiki-page
  - title: World
    menu:
    - id: world
      title: World
      route: wiki-page
    - id: world:citizens
      title: Citizens
      route: wiki-page
    - id: world:creatures
      title: Creatures
      route: wiki-page
    - divider: true
    - id: world:virtue
      title: Virtue
      route: wiki-page
    - id: world:beyond_virtue
      title: Beyond Virtue
      route: wiki-page
    - id: world:nile
      title: NILE
      route: wiki-page
    - divider: true
    - id: world:technology
      title: Technology
      route: wiki-page
    - id: world:serums
      title: Serums
      route: wiki-page
    - id: world:society
      title: Society
      route: wiki-page
    - divider: true
    - id: faq
      title: FAQ
      route: wiki-page
  - title: Play
    menu:
    - title: Play
      route: play
    - title: Active Scenes
      route: scenes-live
    - title: Unshared Scenes
      route: scenes-unshared
    - title: Start New Scene
      route: scene-create
    - title: Combats
      route: combats
  - title: Story
    menu:
    - title: Scenes
      route: scenes
    - divider: true
    - id: system:bounties_oneshot
      title: Bounties & One-Shot Adventures
      route: wiki-page
    - id: system:prps
      title: Player-Run Plots
      route: wiki-page
  - title: Directory
    menu:
    - title: Characters
      route: characters
    - id: dangers
      title: Dangers
      route: wiki-page
    - divider: true
    - title: Players
      route: players
    - title: Game Admin
      route: admins
    - title: Census
      route: census
    - title: Roster
      route: roster
    - title: Locations
      route: locations
    - title: Combats
      route: combats
    - divider: true
    - title: Files
      route: files
  - title: System
    menu:
    - id: guide:custom_mechanics
      title: Custom Mechanics
      route: wiki-page
    - divider: true
    - id: system:xp
      title: XP
      route: wiki-page
    - id: system:luck_points
      title: Luck Points
      route: wiki-page
    - divider: true
    - title: Abilities and Skills
      route: fs3skills-abilities
    - title: Gear List
      route: fs3combat-gear
    - divider: true
    - title: Achievements
      route: achievements
    - title: Skill Limits
      route: fs3-limits
    - title: Skill Scan
      route: fs3skills-scan
    - divider: true
    - title: Heal Scan
      route: heal-scan
  - title: Wiki
    roles:
    - admin
    menu:
    - title: Home
      route: wiki
    - divider: true
    - title: Create New Page
      route: wiki-create
    - title: All Pages
      route: wiki-all
    - title: Search Wiki
      route: search-wiki
    - title: Tags
      route: wiki-tags
    - title: Recent Changes
      route: recent-changes
    - divider: true
    - title: Files
      route: files
    - id: markdown
      title: Editing Help
      route: help-topic
    - title: Wiki Archive
      route: wiki-archive
  - title: Help
    menu:
    - title: Requests
      route: jobs
    - title: Account
      route: account
    - divider: true
    - title: Game Help
      route: help
    - title: Search
      route: search-wiki
    - id: markdown
      title: Markdown Reference
      route: help-topic
    - title: Emoji Reference
      route: emoji
    - title: Terms of Service
      route: tos
  - title: Admin
    roles:
    - admin
    - coder
    menu:
    - title: Jobs
      route: jobs
    - title: Setup
      route: setup
    - title: Manage
      route: manage
    - title: Logs
      route: logs
    - title: Files
      route: files
    - title: Roles
      route: roles
    - title: Server
      route: server-info
  - title: Code
    roles:
    - coder
    menu:
    - title: Tinker
      route: tinker
    - title: Custom Code
      route: custom-code
  - title: Theme
    roles:
    - admin
    menu:
    - title: Theme Colors
      route: setup-colors
    - title: Custom Styles
      route: textfile
      ids:
      - style
      - custom_style.scss
    - title: Custom Fonts
      route: textfile
      ids:
      - style
      - fonts.scss
    - title: Files
      route: files
    - title: Home Page Text
      route: textfile
      ids:
      - text
      - website.txt
    - title: Rainbow Colors
      route: textfile
      ids:
      - style
      - rainbow.scss
  - title: "<i class='fas fa-magnifying-glass'/>"
    menu:
    - title: Search Characters
      route: search-chars
    - title: Search Scenes
      route: search-scenes
    - title: Search Locations
      route: search-locations
    - title: Search Wiki
      route: search-wiki
    - title: Search Help
      route: search-help
    - title: Search Forum
      route: search-forum
    - title: Search Jobs/Requests
      route: search-jobs
  website_code_path: "/home/ares/ares-webportal"
  wiki_aliases:
    main: home
  permissions:
    manage_theme: Edit web portal CSS, colors, and theme images.
    manage_wiki: Create and delete restricted wiki pages and override folder and file
      upload limits.
  uploadable_extensions:
  - ".jpg"
  - ".png"
  - ".gif"
  - ".jpeg"
  auto_wiki_export: true
  wiki_export_cron:
    day_of_week:
    - Tue
    hour:
    - 4
    minute:
    - 37
  char_backup_cleanup_cron:
    hour:
    - 3
    minute:
    - 14
  shortcuts:
    wiki: website
    website/archive: website/export
  hide_searchbox: true
