---
fs3skills:
  action_dots_beyond_chargen_max: 5
  allow_advantages_xp: false
  attr_dots_beyond_chargen_max: 2
  advantage_dots_beyond_chargen_max: 2
  days_between_learning: 30
  max_xp_hoard: 4
  periodic_xp: 1
  xp_costs:
    language:
      '1': 4
      '2': 12
    action:
      '1': 2
      '2': 4
      '3': 6
      '4': 12
      '5': 16
      '6': 16
      '7': 24
    background:
      '1': 6
      '2': 10
    attribute:
      '1': 2
      '2': 8
      '3': 12
    advantage:
      '1': 4
      '2': 12
  xp_cron:
    day_of_week:
    - Sat
    hour:
    - 21
    minute:
    - 0
